# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScapePlayer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=13)),
                ('duration', models.BigIntegerField()),
                ('donator', models.IntegerField()),
                ('staff', models.IntegerField()),
            ],
            options={
                'ordering': ['duration'],
            },
        ),
    ]
