version: "2"

services:
  nginx:
    restart: always
    image: nginx:1.13
    container_name: nginx-container
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
    networks:
      - nginx_network

  django:
    restart: always
    build: ./site/
    env_file: ./site/environment.env
    volumes:
      - ./site/:/opt/services/thiccsite/src
    depends_on: 
     - mysql-site
    networks:
     - nginx_network
     - mysql1_network

  mysql-site:
    restart: always
    image: mysql:5.7.19
    volumes:
      - /opt/services/sitedb/:/var/lib/mysql
    env_file:
      - ./mysql/thiccsite/environment.env
    expose:
      - "3306"
    networks:
      - mysql1_network

  mysql-l4dstats:
    restart: always
    image: mysql:5.7.19
    volumes:
      - /opt/services/l4dstatsdb/:/var/lib/mysql
    env_file:
      - ./mysql/l4dstats/environment.env
    expose:
      - "3306"
    networks:
      - mysq2_network

  teamspeak:
    image: teamspeak
    ports:
      - "9987:9987/udp"
      - "30033:30033"
      - "10011:10011"
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - /data/teamspeak3:/var/ts3server/
    restart: always

#  l4d2:
#    build: ./game-servers/l4d2
#    volumes: 
#      - ./l4d2/cfg:/opt/services/l4d2/left4dead2/cfg
#      - ./l4d2/addons:/opt/services/l4d2/left4dead2/addons
#    restart: always
#    networks:
#      - nginx_network
#      - mysql_network

networks:
  nginx_network:
    driver: bridge
  mysql1_network:
    driver: bridge
  mysq2_network:
    driver: bridge

