# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb_forum', '0004_auto_20181010_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(default='', verbose_name='Avatar'),
        ),
    ]
