# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb_forum', '0005_auto_20181124_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_subscribe',
            field=models.BooleanField(default=True, help_text='Auto subscribe all topics you have created or reply.', verbose_name='Auto subscribe'),
        ),
    ]
