# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb_forum', '0006_auto_20181126_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_unsubscribed',
            field=models.BooleanField(default=False, verbose_name='Is Unsubscribed to Emails'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Is Email verified'),
        ),
    ]
