# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobb_forum', '0007_auto_20181126_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='default', max_length=80, verbose_name='Theme'),
        ),
    ]
