# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='updated_at',
        ),
    ]
