# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-27 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20181227_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='l4d2_award_hunter',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='l4d2_award_left4dead',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='l4d2_award_letinsafehouse',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='l4d2_award_smoker',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='l4d2_award_tankkillnodeaths',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
