global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'first_prometheus_test'

rule_files:
  - 'prometheus.rules.yml'
  - 'alert.rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'django'
    scrape_interval: 5s
    static_configs:
      - targets: ['django']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
    # dns_sd_configs:
    #- names:
    #  - 'tasks.cadvisor'
    #  type: 'A'
    #  port: 8080

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
    # dns_sd_configs:
    #- names:
    #  - 'tasks.node-exporter'
    #  type: 'A'
    #  port: 9100
