# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-06 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_body_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='body_html',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
