# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20181202_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumdonation',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
