# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='platform',
            field=models.IntegerField(choices=[(76, 'Linux'), (108, 'Linux'), (109, 'Mac OS X'), (111, 'Mac OS X'), (119, 'Windows')]),
        ),
        migrations.AlterField(
            model_name='info',
            name='server_type',
            field=models.IntegerField(choices=[(68, 'Dedicated'), (100, 'Dedicated'), (108, 'Non-dedicated'), (112, 'SourceTV')]),
        ),
        migrations.AlterField(
            model_name='info',
            name='version',
            field=models.CharField(max_length=400),
        ),
    ]
