# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0002_auto_20181107_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='version',
            field=models.CharField(max_length=4000),
        ),
    ]
