# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_info', '0003_auto_20181107_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='cvar',
            field=models.CharField(max_length=640),
        ),
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(max_length=640),
        ),
    ]
