# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-29 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64, unique=True)),
                ('authid', models.CharField(max_length=64, unique=True)),
                ('srv_flags', models.CharField(max_length=64)),
                ('immunity', models.IntegerField(default=50)),
                ('aid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban_admin', to=settings.AUTH_USER_MODEL, verbose_name='FooBar Admin')),
            ],
            options={
                'ordering': ['aid'],
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32, null=True)),
                ('authid', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('created', models.IntegerField()),
                ('ends', models.IntegerField()),
                ('length', models.IntegerField()),
                ('reason', models.TextField()),
                ('aid', models.IntegerField()),
                ('adminIp', models.CharField(max_length=32)),
                ('sid', models.IntegerField()),
                ('country', models.CharField(max_length=4, null=True)),
                ('RemovedBy', models.IntegerField(null=True)),
                ('RemoveType', models.CharField(max_length=3, null=True)),
                ('RemovedOn', models.IntegerField(null=True)),
                ('type', models.SmallIntegerField()),
                ('ureason', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Game-only Ban',
                'verbose_name_plural': 'Game-only Bans',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=32)),
                ('created', models.IntegerField()),
                ('comment', models.TextField()),
                ('ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bans.Ban', verbose_name='Ban')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_commenter', to=settings.AUTH_USER_MODEL, verbose_name='Commenter')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flags', models.CharField(max_length=32)),
                ('immunity', models.IntegerField()),
                ('name', models.CharField(max_length=120, unique=True)),
                ('textual_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='srv_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_group', to='bans.Group', verbose_name='Group'),
        ),
    ]
