# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-30 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='sid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ban',
            name='type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
