# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-11 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bans', '0002_auto_20170730_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['aid'], 'verbose_name': 'In-Game Admin', 'verbose_name_plural': 'In-Game Admins'},
        ),
    ]
