# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-24 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bans', '0003_auto_20181010_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='aid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ban_admin', to=settings.AUTH_USER_MODEL, verbose_name='Thicc Admin'),
        ),
    ]
